REC_TIME = 5 #in seconds
SAMPLE_RATE = 8000 #in Hz

CHANNELS = 2
WAV_SIZE = 16 #in bits
WAV_SIZE_BYTE = WAV_SIZE // 8 #in bytes
MIC_BUFFER_SIZE = 4096 #in bytes
MEM_BUFFER_SIZE = MIC_BUFFER_SIZE // 2 #in bytes (32/16=2)
NUM_BYTE_WRITE = REC_TIME * SAMPLE_RATE * WAV_SIZE_BYTE * CHANNELS
SAMPLES_DMA = 256
